name: 'Terraform'

on:
  workflow_dispatch:
    inputs:
        ami_id:
            description: 'AMI ID'
            required: true
            type: string          

jobs:
  terraform_build:
    name: 'Terraform Plan Format and Validate'
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
        working-directory: ./terraform

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: "1.1.7"

    - name: Terraform Init
      run: terraform init

    - name: Terraform Format
      run: terraform fmt -check

    - name: Terraform Plan
      run: |
        terraform plan \
            -var "region=${{ secrets.AWS_REGION }}" \
            -var "aws_access_key=${{ secrets.AWS_ACCESS_KEY_ID }}" \
            -var "aws_secret_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}"
            -var "ami_id=${{ github.event.inputs.ami_id }}"    
        

